# templates/ts-configmap.yml (THE WINNING VERSION)
apiVersion: v1
kind: ConfigMap
metadata:
  name: torchserve-config
  namespace: {{ .Release.Namespace }}
data:
  config.properties: |
    # Enable gRPC by defining the ports
    grpc_inference_port={{ .Values.torchserve.grpc_inference_port }}
    grpc_management_port={{ .Values.torchserve.grpc_management_port }}
    enable_grpc_reflection=true # <-- Add this line


    # The REST API is disabled by simply not defining its address.
    
    # Other essential settings
    model_store=/home/model-server/model-store
    load_models=all